### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by Artemis3v** [RDCH106/pycoinmon#12]
I was using the monitor fine until yesterday, but now its only spitting this error:

```
Traceback (most recent call last):
  File "/usr/bin/pycoinmon", line 11, in <module>
    load_entry_point('pycoinmon==0.4.8', 'console_scripts', 'pycoinmon')()
  File "/usr/lib/python3.7/site-packages/pycoinmon/main.py", line 7, in main
    pycoinmon.core.PyCoinmon().run()
  File "/usr/lib/python3.7/site-packages/pycoinmon/core.py", line 109, in run
    self.print_values()
  File "/usr/lib/python3.7/site-packages/pycoinmon/core.py", line 91, in print_values
    tabulated_data = process_data(filtered_data, currency=self.args.currency, humanize=self.args.humanize)
  File "/usr/lib/python3.7/site-packages/pycoinmon/common.py", line 74, in process_data
    tab_item.append(item[field])
TypeError: string indices must be integers
```
And doesn't work anymore...

**Comment by RDCH106** [comment]
Could you provide pycoinmon version and arguments given to pycoinmon command?

You can check pycoinmon version using the following command:

```
pycoinmon --version
```

**Comment by BrencelJ** [comment]
Hello, I have a similar error message:
Traceback (most recent call last):
  File "/home/pi/.local/bin/pycoinmon", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python2.7/site-packages/pycoinmon/main.py", line 7, in main
    pycoinmon.core.PyCoinmon().run()
  File "/home/pi/.local/lib/python2.7/site-packages/pycoinmon/core.py", line 109, in run
    self.print_values()
  File "/home/pi/.local/lib/python2.7/site-packages/pycoinmon/core.py", line 88, in print_values
    filtered_data = find_data(response.json(), self.args.symbol)
  File "/home/pi/.local/lib/python2.7/site-packages/pycoinmon/common.py", line 85, in find_data
    if item['symbol'] in symbols:
TypeError: string indices must be integers

I'm running version 0.4.8.

Could be a problem because I'm running it on RP or with python-2.7?

**Comment by RDCH106** [comment]
@Artemis3v It seems a problem with coinmarketcap API.

Fixing the problem, it will work again. I will check it next days.

@BrencelJ  I recommend you migrate to 🐍 Python3 if it is possible.

**Comment by RDCH106** [comment]
Issue detected:

```json
{
   "statusCode":410,
   "error":"Gone",
   "message":"WARNING: This API is now offline. Please switch to the new CoinMarketCap API. (https://pro.coinmarketcap.com/migrate/)"
}
```
⚠️ As coinmarketcap API is only free with API keys, I going to try to use coincap API.
