### ISSUE TITLE
Fresh Install, pycoinmon not running, gives traceback "JSONDecodeError"

### ISSUE THREAD

**Issue by geektechniquestudios** [RDCH106/pycoinmon#14]
> Traceback (most recent call last):
  File "/home/no/.local/bin/pycoinmon", line 8, in <module>
    sys.exit(main())
  File "/home/no/.local/lib/python3.8/site-packages/pycoinmon/main.py", line 7, in main
    pycoinmon.core.PyCoinmon().run()
  File "/home/no/.local/lib/python3.8/site-packages/pycoinmon/core.py", line 109, in run
    self.print_values()
  File "/home/no/.local/lib/python3.8/site-packages/pycoinmon/core.py", line 90, in print_values
    filtered_data = response.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I ran the program with no arguments. Just wanted to report on what's I experienced. I'm using python 3.8.5

**Comment by RDCH106** [comment]
@geektechniquestudios  as you can read in README of the repository:

> ⚠️ Pycoinmon will be out of service until the migration to the new CoinCap API is performed.

You can try to fix it. At the moment I don't have time to fix it. 
Sorry for the inconvenience.

**Comment by geektechniquestudios** [comment]
> @geektechniquestudios as you can read in README of the repository:
> 
> > warning Pycoinmon will be out of service until the migration to the new CoinCap API is performed.
> 
> You can try to fix it. At the moment I don't have time to fix it.
> Sorry for the inconvenience.

Ah, thanks. I don't know how I didn't see that. My mistake.
